<a href="https://colab.research.google.com/github/valsson-group/python-bootcamp/blob/main/Summer-2025/Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Summer Bootcamp from Valsson Research Group

### Session 2: Data Analysis and plotting using Python - Numpy, Matplotlib, Seaborn, and Pandas

Date: 06/23/2025

## Mentors:
* Shikshya Bhusal
* Sara Alinejad
* Pradip Si
* Logan Estridge
* Kriti Alam



## Materials for learning Python (along with this workshop)



1.   MolSSI Python Resources for Scientific Python Computing
     (https://education.molssi.org/resources.html#programming)

2.   The Python documentation (https://docs.python.org/3/)

3.   CodeAcademy (Has good learning interface) : https://www.codecademy.com/learn/learn-python

4.  Python for Everybody (https://www.py4e.com/)





## Basic Syntax

In [ ]:
# Lines starting with a hash/pound sign are comments
# meaning that they are not evaluated as code.
#
# Comments are useful to add short (and not so short)
# blurbs of text explaning a particular part of your code

## Recap on last week materials


*   Basics (always!!)
*   Lists
*   Functions (will be covered today)
*   Loops



## Resources for today's session

Documentation of the packages to be used today

*   `numpy` : https://numpy.org/doc/stable/user/absolute_beginners.html
*   `matplotlib` : https://matplotlib.org/stable/users/explain/quick_start.html
*   `seaborn` : https://seaborn.pydata.org/api.html
*   `pandas` :  https://pandas.pydata.org/docs/

More links:

* [MolSSI tutorial on plotting/visualization using Python](https://https://education.molssi.org/python-visualization/matplotlib/matplotlib-procedural.html)




# Function
1. Functions allow us to break down complex problems into smaller.
2. Instead of repeating the same code, we can write it once as a function and reuse it whenever needed.

In [ ]:
import math

In [ ]:
math.

**Exercise 1** Complete the following piece of code to calculate the volume of a cylinder given its radius and height , following the formula: $volume = {pi} * {r}^{2}* {h} $.

Use the value of `pi` stored in the `math` module as `math.pi`.

In [ ]:
volume = math.pi *  (3** 2) * 4
volume

113.09733552923255

In [ ]:
def func_name(arguments):
  "operations"
  return values

In [ ]:
def cylinder_volume(radius, height):
    import math
    volume = math.pi * radius ** 2 * height
    return volume

In [ ]:
cylinder_volume(height=4,radius=3)

113.09733552923255

Lets calculate surface area also and return both volume and surface area.
Calculate surface area with the following the formula: $surface area = 2 *{pi} * {r}* {h} + 2 *{pi} * {r}^{2}$.

In [ ]:
def cylinder_volume_surface(radius, height):
    import math
    volume = math.pi * radius ** 2 * height
    surface_area = 2 * math.pi * radius * height + 2 * math.pi * radius ** 2
    return volume, surface_area

In [ ]:
a, b = cylinder_volume_surface(4 ,5)

In [ ]:
a

251.32741228718345

Function with a default argument

**Calculate interest**

In [ ]:
def calculate_final_amount(initial, years, rate=0.05):

    interest = (initial * rate * years)
    final_amount = initial + interest
    return interest, final_amount

In [ ]:
calculate_final_amount(1000, 2)

(100.0, 1100.0)

In [ ]:
calculate_final_amount(1000, 2, 0.1)

(200.0, 1200.0)

In [ ]:
def add(a, b, verbose=False):
    result = a + b
    if verbose:
        print(f"Adding {a} and {b} gives {result}")
    return result

In [ ]:
add(3, 5, verbose=True)

Adding 3 and 5 gives 8


8

### function to check if a number is divisible by 3.

In [ ]:
def divisible_by_3(number):
    if int(number) % 3 == 0 :
        print(f"{number} is divisible by 3")
    else:
        print(f"{number} is not divisible by 3")

In [ ]:
divisible_by_3(15)

15 is divisible by 3


**Exercise 2** Let's calculate average and standard deviation from a list of numbers.  
Use the following formulas:

- Average: $\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i$  
- Varience: $\sigma^{2}= \frac{1}{n - 1} \sum_{i=1}^{n} (x_i - \bar{x})^2 $
- Standard Deviation: $\sigma = \sqrt{ variance }$

In [ ]:
def compute_avg_std(...):
    import math
    # length of the list
    n= len(...)
    # calculate mean
    avg = sum(...) / ....

    # calculate variance using a loop
    squared_diff_sum = 0
    for num in ...:
        squared_diff_sum += (...) ** 2
    variance = (...)

    stddev = math.sqrt(...)

    return avg, stddev

In [ ]:
import random
random_list = []
for i in range(100):
    random_list.append(random.randint(1,100))

In [ ]:
compute_avg_std(random_list)

## Numpy

In [ ]:
# importing the package

import numpy as np

What does the package do ?
Lets recap what we did for an unknown package last week.

In [ ]:
...(np)

Numpy can be extrememly useful in terms of easy manipulation of data. It facilititates store, manipulate or read data.

### **Defining a Numpy Array**

In [ ]:
int_array=np.array([4,5,6])
float_array=np.array([4.0,5.0,6.0])
string_array=np.array(['4','5','6'])

print(int_array)
print(float_array)
print(string_array)

[4 5 6]
[4. 5. 6.]
['4' '5' '6']


In [ ]:
# Lets show the types of the arrays we defined

print(type(int_array),type(float_array),type(string_array))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


All of them are arrays as defined by numpy

Would be a good idea to use another object called `dtype`

In [ ]:
print(int_array.dtype,float_array.dtype,string_array.dtype)

int64 float64 <U1


### **What are numpy arrays?**

Features similar to lists
*   ordered
*   indexed
*   mutable
*   allowing duplicates

Differences include:

*   All elements should have the same datatype (no mixing like lists)
*   Allows mathematical operations


Lets explore them in details





In [ ]:
# array 1: has all datatypes of elements same

str_array=np.array(['1','2','3'])
print(str_array)
print(str_array.dtype)

['1' '2' '3']
<U1


In [ ]:
# array 2: mixing dataype

mix_array=np.array([1,2,'3'])
print(mix_array)
print(mix_array.dtype)

['1' '2' '3']
<U21


Notice here that the datatype of the last element (here '3' which is a string) is considered over the whole datatype

Things werent this way when it was a list

In [ ]:
mixed_list=['1',2,3.0]
print(mixed_list)
print(type(mixed_list))
print(type(mixed_list[0]),type(mixed_list[1]),type(mixed_list[2]))

['1', 2, 3.0]
<class 'list'>
<class 'str'> <class 'int'> <class 'float'>


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [ ]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [ ]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

### Different ways to generate array

In [ ]:
list = [1, 2, 3]
sample_array = np.array(list)
sample_array

array([1, 2, 3])

In [ ]:
ones = np.zeros((5,4))
ones

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

In [ ]:
# start, stop, and increments of step
range_array = np.arange(0, 10,2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
# Generate 5 evenly spaced numbers between 0 and 10 (inclusive)
arr1 = np.linspace(0, 10, 10) #endpoint=False
print(arr1)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 9, 2, 6, 4],
       [7, 3, 6, 5, 9],
       [5, 9, 0, 2, 6]])

In [ ]:
random_array.size
random_array.shape

(3, 5)

In [ ]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.51300023, 0.07997883, 0.05928369],
       [0.81343428, 0.06795338, 0.33570047],
       [0.84654642, 0.47996889, 0.53948741],
       [0.11086935, 0.63743722, 0.2693089 ],
       [0.16229083, 0.69649925, 0.58280742]])

In [ ]:
#np.random.seed(seed=99999)
random_array_4 = np.random.randint(1,10, size=(5, 3))
random_array_4

array([[5, 8, 5],
       [2, 1, 3],
       [8, 1, 6],
       [2, 6, 6],
       [3, 8, 8]])

In [ ]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.89154299, 0.51028416, 0.12991877],
       [0.76826067, 0.51064723, 0.68202018],
       [0.93722732, 0.01411322, 0.30856444],
       [0.62736904, 0.06218295, 0.20951688],
       [0.24570667, 0.63153783, 0.17239976]])

In [ ]:
Z = np.diag(1+np.arange(4),k=-1) # k=1, 0
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Slicing array with index

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1:, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# replace an element
a[2][2] = 0
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  0, 12]])

In [ ]:
b = a[1:3, 1:3]
b

array([[ 6,  7],
       [10,  0]])

**Excercise2** Create a 2d array with 1 on the border and 0 inside

In [ ]:
Z = np.ones((...,...))
Z

In [ ]:
Z[:,:] = 0
print(Z)

Mathematical Operations: Lists vs Numpy Arrays

In [ ]:
a_list=[1,2,1]
b_list=[5,2,1]

add_list=a_list+b_list
print(add_list)

[1, 2, 1, 5, 2, 1]


We dont really "add" them

Rather we concatenate them

To actually "add" them we might need a `for` loop

In [ ]:
add_list=[]

for x in range(len(a_list)):   # warning while selecting the range
  add_list.append(a_list[x]+b_list[x])

print(add_list)

[6, 4, 2]


Or we can do it using `numpy` arrays

In [ ]:
a_array=np.array(a_list)
b_array=np.array(b_list)

add_array=a_array+b_array   # here we "add"
print(add_array)

[6 4 2]


The `np.concatenate` will help join the arrays

In [ ]:
print(a_list,b_list)
print(np.concatenate((a_array,b_array)))


[1, 2, 1] [5, 2, 1]
[1 2 1 5 2 1]


### Element-wise mathematical operations with numpy

In [ ]:
a_array=np.array([1,2,3])
b_array=np.array([4,5,6]) # both have the same size

print(a_array+b_array)
print(a_array-b_array)
print(a_array*b_array)
print(a_array/b_array)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


What if we do not have the same size?

In [ ]:
a_array=np.array([1,2,3])
b_array=np.array([4,5]) # both do not have the same size

print(a_array+b_array)
print(a_array-b_array)
print(a_array*b_array)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [ ]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1+a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [ ]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [ ]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [ ]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array

array([0.15070371, 0.40403515, 0.03354055, ..., 0.56102712, 0.99856718,
       0.68070437])

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

10.5 ms ± 1.71 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
44.2 µs ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
print(np.mean(massive_array))
print(np.max(massive_array))
print(np.min(massive_array))
print(np.std(massive_array))
print(np.var(massive_array))


0.4985743851976818
0.9999795096387298
1.1107155901690646e-05
0.2887918432383325
0.0834007287209936


In [ ]:
#matrix mutiplication
Z = np.matmul(np.ones((5, 4)), np.ones((3, 2)))
print(Z)



In [ ]:
## alternative way
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

### Reshaping & transposing

In [ ]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2.shape

(2, 3)

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape.shape

(2, 3, 1)

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [ ]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
#np.random.seed(4)
A = np.random.randint(0,2,5)
#np.random.seed(4)
B = np.random.randint(0,2,5)
print(A)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

[1 1 0 0 1]
[0 0 1 1 0]
False


In [ ]:
arr = np.array([40, 10, 20, 30])
sorted_indices = np.argsort(arr)

print("Original array:", arr)
print("Indices that would sort the array:", sorted_indices)
print("Sorted array using indices:", arr[sorted_indices])

Original array: [40 10 20 30]
Indices that would sort the array: [1 2 3 0]
Sorted array using indices: [10 20 30 40]


### Define a vectorized function

In [ ]:
import numpy as np
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [ ]:
myfunc(3,4)

7

In [ ]:
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)
#vfunc(2, [1, 2, 3, 4])


array([3, 4, 1, 2])

**Execise** using linspace make an array of 1000 elements from -pi to pi. And plot sin, cos function

In [ ]:
arr1 = np.linspace(-5, 5, 500)
print(arr1)

In [ ]:
sin_vals = np.sin(arr1)
cos_vals = np.cos(arr1)

In [ ]:
import matplotlib.pyplot as plt
plt.plot(arr1, sin_vals, label='sin(x)', color='blue')
plt.plot(arr1, cos_vals, label='cos(x)', color='green')

##Lets Plot!!!
###Matplotlib

**Matplotlib** is one of the most popular Python libraries used for creating static, animated, and interactive visualizations. It is  especially useful for:
- Understanding patterns in data
- Sharing insights through visuals
- Making your projects look more professional!

In this lesson, we’ll use `matplotlib.pyplot`, a part of the matplotlib library, which works very similarly to drawing charts by hand—but with code!


In [ ]:
# Importing the library
import matplotlib.pyplot as plt

## Line Plot

In [ ]:
# Sample data
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

# Plotting the data
plt.plot(x, y)

# Adding labels
plt.title("Line Plot Example")
plt.xlabel("X values")
plt.ylabel("Y values")

# Show the plot
plt.show()

## Bar Chart

In [ ]:
# Categories and their values
categories = ['Apples', 'Bananas', 'Cherries']
values = [10, 15, 7]

plt.bar(categories, values)
plt.title("Fruit Count")
plt.ylabel("Quantity")
plt.show()

## Scatter Plot

In [ ]:
x = [1, 2, 3, 4, 5]
y = [5, 7, 6, 8, 7]

plt.scatter(x, y, color='green')
plt.title("Scatter Plot Example")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()

## Lets load and plot from a file

In [101]:
#download the required file from GitHub (raw URL)
url = "https://raw.githubusercontent.com/valsson-group/python-bootcamp/main/Summer-2025/Data/TimeSeries_Dataset-3.data"


In [102]:
import numpy as np
# Load the file (skip the header row)
data = np.loadtxt(url, skiprows=1)

In [ ]:
# Split into columns
time_ns = data[:, 0]
variable = data[:, 1]

# Plot
plt.figure(figsize=(15, 10))
plt.plot(time_ns, variable)
plt.title("Time Series Data")
plt.xlabel("Time (ns)")
plt.ylabel("Variable")
#plt.grid(True)
plt.show()

In [ ]:
plt.hist(variable, density=True, bins=500, alpha=1)
plt.title("Time Series Data")
plt.xlabel("Time (ns)")
plt.ylabel("Variable")
#plt.grid(True)
plt.show()

* A bin is like a container or range for values.
bins=500 means:Split the range of data into 500 small intervals, and count how many values fall into each.


* Normally, a histogram shows counts (how many values in each bin). With density=True, it instead shows a probability density:The total area under the histogram = 1, not the total number of data points.


* alpha controls transparency (range: 0 to 1)alpha=1 means:The histogram is fully opaque (solid color).
alpha=0.5 would make it semi-transparent



In [ ]:
import seaborn as sns
plt.rcParams['figure.dpi'] = 500
plt.hist(variable, density=True, bins=500, alpha=0.5)
sns.kdeplot(variable, bw_adjust=0.3)
plt.title("Time Series Data")
plt.xlabel("Time (ns)")
plt.ylabel("Variable")
plt.show()

In [ ]:
#Download the file from GitHub (raw URL)
https://raw.githubusercontent.com/valsson-group/python-bootcamp/main/Summer-2025/Data/Azobenzene-cis_B3LYP.data

In [ ]:
import numpy as np

# Load the file (skip the header row)
data = np.loadtxt("Azobenzene-cis_B3LYP.data", skiprows=1)

# Split into columns
states = data[:, 0]
excitation_energy = data[:, 1]     # x-axis
oscillator_strength = data[:, 2]   # y-axis

# Plot as a line plot
plt.figure(figsize=(15, 6))
#plt.plot(states, oscillator_strength, color='navy', marker='o', linestyle='-.', linewidth=2)
#plt.plot(states, excitation_energy, color='navy', marker='o', linestyle='-', linewidth=2)
plt.plot(excitation_energy, oscillator_strength, color='navy', marker='o', linestyle='-', linewidth=2)

# Title and labels
plt.title("Excitation Spectrum of Azobenzene (cis, B3LYP)", fontsize=16)
plt.xlabel("states)")
plt.ylabel("Excitation Energy (eV)")
#plt.ylabel("Oscillator Strength
#plt.grid(True)
plt.show()

## Sub-plots

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Load data with NumPy
data = np.loadtxt("Azobenzene-cis_B3LYP.data", skiprows=1)
states = data[:, 0]
excitation_energy = data[:, 1]
oscillator_strength = data[:, 2]


# Create subplots
fig, axs = plt.subplots(2, 1, figsize=(10, 5), sharex=True)

# Plot1
axs[0].plot(states, excitation_energy, 'o-', color='navy', linewidth=2)
axs[0].set_title("Excitation Spectrum of Azobenzene (cis, B3LYP)")
axs[0].set_ylabel("Oscillator Strength")
axs[0].grid(True)

# Plot2
axs[1].plot(states, oscillator_strength, 's--', color='darkgreen', linewidth=2)
axs[1].set_title("Oscillator Strength (Example)")
axs[1].set_xlabel("Excitation Energy (eV)")
axs[1].set_ylabel("Oscillator Strength (scaled)")
axs[1].grid(True)

plt.tight_layout()
plt.show()
